//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 01:50:16 PM IST 
//


package org.iisc.mile.ocr.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.iisc.mile.ocr.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Page_QNAME = new QName("http://mile.ee.iisc.ernet.in/schemas/ocr_output", "page");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.iisc.mile.ocr.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OcrPage }
     * 
     */
    public OcrPage createOcrPage() {
        return new OcrPage();
    }

    /**
     * Create an instance of {@link OcrRectangle }
     * 
     */
    public OcrRectangle createOcrRectangle() {
        return new OcrRectangle();
    }

    /**
     * Create an instance of {@link OcrBlock }
     * 
     */
    public OcrBlock createOcrBlock() {
        return new OcrBlock();
    }

    /**
     * Create an instance of {@link OcrLine }
     * 
     */
    public OcrLine createOcrLine() {
        return new OcrLine();
    }

    /**
     * Create an instance of {@link OcrWord }
     * 
     */
    public OcrWord createOcrWord() {
        return new OcrWord();
    }

    /**
     * Create an instance of {@link OcrSymbol }
     * 
     */
    public OcrSymbol createOcrSymbol() {
        return new OcrSymbol();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OcrPage }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OcrPage }{@code >}
     */
    @XmlElementDecl(namespace = "http://mile.ee.iisc.ernet.in/schemas/ocr_output", name = "page")
    public JAXBElement<OcrPage> createPage(OcrPage value) {
        return new JAXBElement<OcrPage>(_Page_QNAME, OcrPage.class, null, value);
    }

}
