//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.16 at 11:59:31 AM GMT+05:30 
//


package org.iisc.mile.ocr.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for blockType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="blockType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://mile.ee.iisc.ernet.in/schemas/ocr_output}rectangleType">
 *       &lt;sequence>
 *         &lt;element name="line" type="{http://mile.ee.iisc.ernet.in/schemas/ocr_output}lineType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="Text|Image"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="BlockNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "blockType", namespace = "http://mile.ee.iisc.ernet.in/schemas/ocr_output", propOrder = {
    "line"
})
public class OcrBlock
    extends OcrRectangle
{
    @XmlElement(namespace = "http://mile.ee.iisc.ernet.in/schemas/ocr_output")
    protected List<OcrLine> line;
    @XmlAttribute(required = true)
    protected String type;
    @XmlAttribute(name = "BlockNumber")
    protected Integer blockNumber;

    public static final String BLOCK_TYPE_TEXT = "Text";
    public static final String BLOCK_TYPE_IMAGE = "Image";

    /**
     * Gets the value of the line property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the line property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OcrLine }
     * 
     * 
     */
    public List<OcrLine> getLine() {
        if (line == null) {
            line = new ArrayList<OcrLine>();
        }
        return this.line;
    }

    public boolean isSetLine() {
        return ((this.line!= null)&&(!this.line.isEmpty()));
    }

    public void unsetLine() {
        this.line = null;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    public boolean isSetType() {
        return (this.type!= null);
    }

    /**
     * Gets the value of the blockNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getBlockNumber() {
        return blockNumber;
    }

    /**
     * Sets the value of the blockNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBlockNumber(int value) {
        this.blockNumber = value;
    }

    public boolean isSetBlockNumber() {
        return (this.blockNumber!= null);
    }

    public void unsetBlockNumber() {
        this.blockNumber = null;
    }

	public static void sortBlocks(List<OcrBlock> blocks) {
		if (blocks != null && !blocks.isEmpty()) {
			Collections.sort(blocks, new Comparator<OcrBlock>() {
				public int compare(OcrBlock o1, OcrBlock o2) {
					return o1.getBlockNumber() - o2.getBlockNumber();
				}
			});
		}
	}

	public void sortLines() {
		OcrLine.sortLines(line);
	}
}
