//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.16 at 11:59:31 AM GMT+05:30 
//


package org.iisc.mile.ocr.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lineType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://mile.ee.iisc.ernet.in/schemas/ocr_output}rectangleType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="word" type="{http://mile.ee.iisc.ernet.in/schemas/ocr_output}wordType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="LineNumber" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lineType", namespace = "http://mile.ee.iisc.ernet.in/schemas/ocr_output", propOrder = {
    "word"
})
public class OcrLine
    extends OcrRectangle
{
    @XmlElement(namespace = "http://mile.ee.iisc.ernet.in/schemas/ocr_output", required = true)
    protected List<OcrWord> word;
    @XmlAttribute(name = "LineNumber")
    protected Integer lineNumber;

    /**
     * Gets the value of the word property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the word property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OcrWord }
     * 
     * 
     */
    public List<OcrWord> getWord() {
        if (word == null) {
            word = new ArrayList<OcrWord>();
        }
        return this.word;
    }

    public boolean isSetWord() {
        return ((this.word!= null)&&(!this.word.isEmpty()));
    }

    public void unsetWord() {
        this.word = null;
    }

    /**
     * Gets the value of the lineNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getLineNumber() {
        return lineNumber;
    }

    /**
     * Sets the value of the lineNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLineNumber(int value) {
        this.lineNumber = value;
    }

    public boolean isSetLineNumber() {
        return (this.lineNumber!= null);
    }

    public void unsetLineNumber() {
        this.lineNumber = null;
    }

	public static void sortLines(List<OcrLine> lines) {
		if (lines != null && !lines.isEmpty()) {
			Collections.sort(lines, new Comparator<OcrLine>() {
				public int compare(OcrLine o1, OcrLine o2) {
					return o1.getLineNumber() - o2.getLineNumber();
				}
			});
		}
	}

	public void sortWords() {
		OcrWord.sortWords(word);
	}
}
