//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.16 at 11:59:31 AM GMT+05:30 
//


package org.iisc.mile.ocr.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for symbolType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="symbolType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://mile.ee.iisc.ernet.in/schemas/ocr_output}rectangleType">
 *       &lt;attribute name="className" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="classGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SymbolNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "symbolType", namespace = "http://mile.ee.iisc.ernet.in/schemas/ocr_output")
public class OcrSymbol
    extends OcrRectangle
{

    @XmlAttribute(required = true)
    protected String className;
    @XmlAttribute(required = true)
    protected String classGroup;
    @XmlAttribute(name = "SymbolNumber")
    protected Integer symbolNumber;

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    public boolean isSetClassName() {
        return (this.className!= null);
    }

    /**
     * Gets the value of the classGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassGroup() {
        return classGroup;
    }

    /**
     * Sets the value of the classGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassGroup(String value) {
        this.classGroup = value;
    }

    public boolean isSetClassGroup() {
        return (this.classGroup!= null);
    }

    /**
     * Gets the value of the symbolNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getSymbolNumber() {
        return symbolNumber;
    }

    /**
     * Sets the value of the symbolNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSymbolNumber(int value) {
        this.symbolNumber = value;
    }

    public boolean isSetSymbolNumber() {
        return (this.symbolNumber!= null);
    }

    public void unsetSymbolNumber() {
        this.symbolNumber = null;
    }

}
