//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.02 at 07:30:10 PM IST 
//


package org.iisc.mile.ocr.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wordType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://mile.ee.iisc.ernet.in/schemas/ocr_output}rectangleType">
 *       &lt;sequence>
 *         &lt;element name="symbol" type="{http://mile.ee.iisc.ernet.in/schemas/ocr_output}symbolType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="unicode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="WordNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="doubtfulRecognition" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wordType", namespace = "http://mile.ee.iisc.ernet.in/schemas/ocr_output", propOrder = {
    "symbol"
})
public class OcrWord
    extends OcrRectangle
{
    @XmlElement(namespace = "http://mile.ee.iisc.ernet.in/schemas/ocr_output")
    protected List<OcrSymbol> symbol;
    @XmlAttribute(name = "unicode", required = true)
    protected String unicode;
    @XmlAttribute(name = "WordNumber")
    protected Integer wordNumber;
    @XmlAttribute(name = "doubtfulRecognition")
    protected Boolean doubtfulRecognition;
    @XmlAttribute(name = "confidenceLevel")
    protected Double confidenceLevel;

    /**
     * Gets the value of the symbol property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the symbol property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSymbol().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OcrSymbol }
     * 
     * 
     */
    public List<OcrSymbol> getSymbol() {
        if (symbol == null) {
            symbol = new ArrayList<OcrSymbol>();
        }
        return this.symbol;
    }

    public boolean isSetSymbol() {
        return ((this.symbol!= null)&&(!this.symbol.isEmpty()));
    }

    public void unsetSymbol() {
        this.symbol = null;
    }

    /**
     * Gets the value of the unicode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnicode() {
        return unicode;
    }

    /**
     * Sets the value of the unicode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnicode(String value) {
        this.unicode = value;
    }

    public boolean isSetUnicode() {
        return (this.unicode!= null);
    }

    /**
     * Gets the value of the wordNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getWordNumber() {
        return wordNumber;
    }

    /**
     * Sets the value of the wordNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWordNumber(int value) {
        this.wordNumber = value;
    }

    public boolean isSetWordNumber() {
        return (this.wordNumber!= null);
    }

    public void unsetWordNumber() {
        this.wordNumber = null;
    }

    /**
     * Gets the value of the doubtfulRecognition property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDoubtfulRecognition() {
		if (!isSetDoubtfulRecognition()) {
			return false;
		}
        return doubtfulRecognition;
    }

    /**
     * Sets the value of the doubtfulRecognition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDoubtfulRecognition(boolean value) {
        this.doubtfulRecognition = value;
    }

    public boolean isSetDoubtfulRecognition() {
        return (this.doubtfulRecognition!= null);
    }

    public void unsetDoubtfulRecognition() {
        this.doubtfulRecognition = null;
    }

    public double getConfidenceLevel() {
		return confidenceLevel;
	}

	public void setConfidenceLevel(double confidenceLevel) {
		this.confidenceLevel = confidenceLevel;
	}

    public boolean isSetConfidenceLevel() {
        return (this.confidenceLevel!= null);
    }

    public void unsetConfidenceLevel() {
        this.confidenceLevel = null;
    }

	public static void sortWords(List<OcrWord> words) {
		if (words != null && !words.isEmpty()) {
			Collections.sort(words, new Comparator<OcrWord>() {
				public int compare(OcrWord o1, OcrWord o2) {
					return o1.getWordNumber() - o2.getWordNumber();
				}
			});
		}
	}
}
